repos:
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.71.1
    hooks:
      - id: cfn-lint-rc
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
